import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { MapPin, Sparkles, Shield, Zap, ArrowRight, Globe, Clock, Users } from 'lucide-react';

const Home: React.FC = () => {
  const { isAuthenticated } = useAuth();

  const features = [
    {
      icon: Sparkles,
      title: 'AI-Powered Planning',
      description: 'Get personalized itineraries generated by advanced AI models including OpenAI GPT and Groq.'
    },
    {
      icon: Shield,
      title: 'Smart Caching',
      description: 'Reuse existing itineraries for same routes with updated dates and budget for instant results.'
    },
    {
      icon: Zap,
      title: 'Flexible Usage',
      description: 'Generate itineraries with or without an account. Registered users get saved plans and history.'
    },
    {
      icon: Globe,
      title: 'Global Coverage',
      description: 'Plan trips anywhere in the world with detailed day-by-day recommendations.'
    },
    {
      icon: Clock,
      title: 'Real-time Updates',
      description: 'Get up-to-date travel information and budget calculations for your destinations.'
    },
    {
      icon: Users,
      title: 'Personal Dashboard',
      description: 'Manage all your travel plans in one place with easy access to your itinerary history.'
    }
  ];

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative py-20 px-4 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary-100 via-white to-secondary-100 opacity-50"></div>
        <div className="relative max-w-7xl mx-auto text-center">
          <div className="mb-8">
            <MapPin className="h-16 w-16 text-primary-600 mx-auto mb-4 animate-bounce-light" />
            <h1 className="text-4xl md:text-6xl font-bold mb-6">
              <span className="bg-gradient-to-r from-primary-600 via-secondary-600 to-accent-500 bg-clip-text text-transparent">
                Plan Your Perfect
              </span>
              <br />
              <span className="text-slate-900">Travel Adventure</span>
            </h1>
            <p className="text-xl text-slate-600 max-w-3xl mx-auto leading-relaxed">
              Generate personalized travel itineraries in seconds with AI-powered recommendations. 
              From budget planning to daily activities, we've got your journey covered.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-12">
            <Link
              to="/generate"
              className="btn btn-primary text-lg px-8 py-3 flex items-center space-x-2 group"
            >
              <span>Start Planning</span>
              <ArrowRight className="h-5 w-5 group-hover:translate-x-1 transition-transform" />
            </Link>
            
            {!isAuthenticated && (
              <Link
                to="/register"
                className="btn btn-secondary text-lg px-8 py-3"
              >
                Sign Up Free
              </Link>
            )}
          </div>

          {/* Stats */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            <div className="text-center">
              <div className="text-3xl font-bold text-primary-600 mb-2">AI-Powered</div>
              <div className="text-slate-600">Multiple AI models for personalized planning</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-secondary-600 mb-2">Instant</div>
              <div className="text-slate-600">Generate detailed itineraries in seconds</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-accent-600 mb-2">Global</div>
              <div className="text-slate-600">Plan trips to any destination worldwide</div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-4 bg-white">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">
              Everything You Need for Perfect Trips
            </h2>
            <p className="text-xl text-slate-600 max-w-2xl mx-auto">
              Our comprehensive travel planning platform combines AI technology with user-friendly design 
              to create unforgettable travel experiences.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => {
              const IconComponent = feature.icon;
              return (
                <div 
                  key={index}
                  className="card hover:shadow-lg hover:shadow-primary-100 transition-all duration-300 group"
                >
                  <div className="flex items-center space-x-3 mb-4">
                    <div className="p-3 bg-primary-100 rounded-lg group-hover:bg-primary-200 transition-colors">
                      <IconComponent className="h-6 w-6 text-primary-600" />
                    </div>
                    <h3 className="text-lg font-semibold text-slate-900">
                      {feature.title}
                    </h3>
                  </div>
                  <p className="text-slate-600 leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4 bg-gradient-to-r from-primary-600 to-secondary-600">
        <div className="max-w-4xl mx-auto text-center text-white">
          <h2 className="text-3xl md:text-4xl font-bold mb-6">
            Ready to Start Your Journey?
          </h2>
          <p className="text-xl mb-8 opacity-90">
            Join thousands of travelers who trust Travel Buddy for their adventure planning.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              to="/generate"
              className="px-8 py-3 bg-white text-primary-600 font-semibold rounded-lg hover:bg-gray-100 transition-colors flex items-center justify-center space-x-2"
            >
              <span>Generate Itinerary</span>
              <ArrowRight className="h-5 w-5" />
            </Link>
            
            {isAuthenticated ? (
              <Link
                to="/dashboard"
                className="px-8 py-3 border-2 border-white text-white font-semibold rounded-lg hover:bg-white hover:text-primary-600 transition-colors"
              >
                View Dashboard
              </Link>
            ) : (
              <Link
                to="/register"
                className="px-8 py-3 border-2 border-white text-white font-semibold rounded-lg hover:bg-white hover:text-primary-600 transition-colors"
              >
                Create Free Account
              </Link>
            )}
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;